### ISSUE TITLE
Directory misnamed

### ISSUE THREAD

**Issue by MinamiFunakoshiTR** [reuters-graphics/bluprint_chart-module-svelte#3]
The line the ReadMe tells you to import into your .js file says:

`` import rolloutChart from '@reuters-graphics/chart-module-vaccine-rollout``

But in the node module, the folder is named just "vaccine-rollout", not "chart-module-vaccine-rollout"

The import line should be fixed so that "chart-module" is omitted. It should look like this:
`` import rolloutChart from '@reuters-graphics/vaccine-rollout'; ``
![Screenshot 2021-02-11 at 12 32 17 PM](https://user-images.githubusercontent.com/62298563/107675299-f2723600-6c65-11eb-9f8e-a9e8d25b21a8.png)

**Comment by hobbes7878** [comment]
Good point! I actually want it to be name-spaced with `chart-module-`. Will fix!
